#!/usr/bin/env python

import sys
import pathlib

thisfile = pathlib.Path(__file__)
sys.path.insert(0, str(thisfile.parent / "firefly_automate"))

import firefly_automate.run_transform_transactions

firefly_automate.run.main()
