#!/usr/bin/env python

import pathlib
import sys

thisfile = pathlib.Path(__file__)
sys.path.insert(0, str(thisfile.parent / "firefly_automate"))

import firefly_automate.run_transform_transactions

firefly_automate.run_transform_transactions.main()
